DROP TABLE IF EXISTS VEHICLE;

CREATE TABLE VEHICLE (
  VIN VARCHAR(20) NOT NULL PRIMARY KEY,
  MAKE VARCHAR(50) NOT NULL,
  MODEL VARCHAR (50) NOT NULL,
  MODEL_YEAR INTEGER,
  VERSION INTEGER
);

INSERT INTO VEHICLE(VIN, MAKE, MODEL, MODEL_YEAR, VERSION) VALUES ('v12345', 'Sedan', 'Toyota', 2014, 1);
INSERT INTO VEHICLE(VIN, MAKE, MODEL, MODEL_YEAR, VERSION) VALUES ('v12346', 'Sedan', 'Suzuki', 2015, 1);