DROP TABLE IF EXISTS VEHICLE_CH01_V1;

CREATE TABLE VEHICLE_CH01_V1 (
  VIN VARCHAR(20) NOT NULL PRIMARY KEY,
  MAKE VARCHAR(50) NOT NULL,
  MODEL VARCHAR (50) NOT NULL,
  MODEL_YEAR INTEGER,
  VERSION INTEGER
);