DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  NAME_OF_BANK VARCHAR(50) NOT NULL,
  ACCT_NO VARCHAR(20) NOT NULL,
  ROUTING_NO VARCHAR(20)
);
