DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATE_TIME DATETIME NOT NULL,
  VERSION INT NOT NULL,
  EMAIL_ADDR VARCHAR(50)
);

CREATE TABLE ADDRESS (
  ID INTEGER NOT NULL PRIMARY KEY,
  STREET VARCHAR(50),
  CITY VARCHAR(50),
  POSTCODE VARCHAR(10),
  STATE VARCHAR(50),
  COUNTRY VARCHAR(50),
  CONSTRAINT ADDRESS_FK FOREIGN KEY(ID) REFERENCES CUSTOMER(ID)
);

