DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EMAIL_ADDR VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  VERSION BIGINT NOT NULL
);

CREATE TABLE ORDERS (
  ORDER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PLACEMENT_TIME DATETIME NOT NULL,
  PRICE NUMERIC(10, 2) NOT NULL,
  CUSTOMER_ID_FK INTEGER NOT NULL,
  VERSION BIGINT NOT NULL,
  CONSTRAINT ORDERS_FK_CONSTR FOREIGN KEY (CUSTOMER_ID_FK) REFERENCES CUSTOMER(CUSTOMER_ID)
);