DROP TABLE IF EXISTS APP_USER;

CREATE TABLE APP_USER (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO APP_USER (user_name, email) VALUES ('shamim', 'shamim.buet.99@gmail.com')