DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATOR VARCHAR(20) NOT NULL,
  CREATE_TS DATETIME NOT NULL,
  UPDATER VARCHAR(20),
  UPDATE_TS DATETIME,
  TITLE VARCHAR(100) NOT NULL,
  PRICE NUMERIC(6,2) NOT NULL 
);