DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CONTENT;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS SEQUENCE_GENERATOR_TBL;
DROP TABLE IF EXISTS PREFERRED_CUSTOMER;

CREATE TABLE ADDRESS (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STREET VARCHAR(50) NOT NULL,
  CITY VARCHAR(20),
  STATE VARCHAR(20) NOT NULL,
  ZIP VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  VERSION INTEGER NOT NULL
);

CREATE TABLE BOOK(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(100)
);

CREATE TABLE CONTENT(
  BOOK_ID INTEGER NOT NULL PRIMARY KEY,
  PDF BLOB NOT NULL,
  CONSTRAINT BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
);

CREATE TABLE ORDERS(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STATUS ENUM('NEW', 'COMPLETE', 'FILLED', 'BILLED') NOT NULL
);

CREATE TABLE SEQUENCE_GENERATOR_TBL (
  SEQUENCE_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
  SEQUENCE_VALUE INTEGER NOT NULL
);

INSERT INTO SEQUENCE_GENERATOR_TBL (SEQUENCE_NAME, SEQUENCE_VALUE) VALUES ('cust_id_seq', 0);

CREATE TABLE PREFERRED_CUSTOMER (
  ID INTEGER NOT NULL PRIMARY KEY,
  EXPIRE_DATE DATE NOT NULL 
);
