DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CONTENT;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE ADDRESS (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  STREET VARCHAR(50) NOT NULL,
  CITY VARCHAR(20),
  STATE VARCHAR(20) NOT NULL,
  ZIP VARCHAR(20) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  VERSION INTEGER NOT NULL
);

CREATE TABLE BOOK(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(100)
);

CREATE TABLE CONTENT(
  BOOK_ID INTEGER NOT NULL PRIMARY KEY,
  PDF BLOB NOT NULL,
  CONSTRAINT BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
);
