DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK(
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CREATE_USER VARCHAR(20) NOT NULL,
  CREATE_TIME DATETIME NOT NULL,
  UPDATE_USER VARCHAR(20),
  UPDATE_TIME DATETIME,
  TITLE VARCHAR(100) NOT NULL,
  PRICE NUMERIC(6,2) NOT NULL 
);