DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  BANK_NAME VARCHAR(50) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
  ROUTING_NUMBER VARCHAR(20)
);
